# This is a general purpose terraform -> ansible inventory template
# Using this template, there are many ways to refer to hosts
#   'all' can be used to refer to all hosts, of course
#   'group_name[0]'
#   name of resource + index
# The k3-* groups should be left in for ansible-k3s, if we want to be able to use it
# if you want to change the template on an existing `terraform apply` or change the inputs, just do another `terraform apply` and the new inventory will be generated
all:
    hosts:
        nferrante-instructor:
            ansible_host: 149.165.155.122
            students:
              instructor:
                password: "GVOUS#illegally#capital#caribou"
                display_number: 6

        nferrante-student:
            ansible_host: 149.165.153.9
            students:
              user1:
                password: "pmC6d#allegedly#liked#frog"
                display_number: 6
    vars:
        CONNECTION_USERNAMES:
          - 'nferrante@access-ci.org'
          - 'ubuntu'
          - 'almalinux'
          - 'rocky'
          - 'centos'
#          - 'debian'
#          - 'fedora'
#          - 'cloud-user'
#          - 'opensuse'
          - 'root'
        SHARE_ENABLE: false
        CSV_EMAIL: ""
        CSV_LOCAL_FILE_PATH: "student_assignments.csv"
        CSV_ASSIGNMENTS_UPLOAD_LOCATION: /opt/student_assignments.csv
    children:
        instructor_instances:
            hosts:
                nferrante-instructor:
